# Generated by Django 5.2.5 on 2025-08-18 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('case_type', models.CharField(choices=[('criminal', 'Criminal'), ('civil', 'Civil'), ('family', 'Family'), ('commercial', 'Commercial'), ('administrative', 'Administrative')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('decided', 'Decided'), ('closed', 'Closed'), ('appealed', 'Appealed')], default='pending', max_length=20)),
                ('plaintiff', models.CharField(max_length=200)),
                ('defendant', models.CharField(max_length=200)),
                ('plaintiff_lawyer', models.CharField(blank=True, max_length=200, null=True)),
                ('defendant_lawyer', models.CharField(blank=True, max_length=200, null=True)),
                ('filing_date', models.DateTimeField(auto_now_add=True)),
                ('hearing_date', models.DateTimeField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('verdict', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-filing_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('final', 'Final Report'), ('interim', 'Interim Report'), ('appeal', 'Appeal Report')], default='final', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='court.case')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Report',
                'verbose_name_plural': 'Case Reports',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('physical', 'Physical Evidence'), ('witness', 'Witness Statement'), ('expert', 'Expert Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_path', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_admissible', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='court.case')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_type', models.CharField(choices=[('preliminary', 'Preliminary Hearing'), ('trial', 'Trial'), ('sentencing', 'Sentencing'), ('appeal', 'Appeal Hearing'), ('review', 'Review Hearing')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('next_hearing_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='court.case')),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_hearings', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hearing',
                'verbose_name_plural': 'Hearings',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
