# Generated by Django 5.2.5 on 2025-08-18 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmate_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('identification_number', models.CharField(max_length=50, unique=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('case_number', models.CharField(max_length=50)),
                ('conviction_date', models.DateField()),
                ('crime_description', models.TextField()),
                ('sentence_type', models.CharField(choices=[('prison', 'Prison Sentence'), ('probation', 'Probation'), ('fine', 'Fine Only'), ('community_service', 'Community Service'), ('life', 'Life Sentence'), ('death', 'Death Penalty')], max_length=20)),
                ('sentence_duration_years', models.IntegerField(blank=True, null=True)),
                ('sentence_duration_months', models.IntegerField(blank=True, null=True)),
                ('sentence_duration_days', models.IntegerField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admission_date', models.DateField()),
                ('expected_release_date', models.DateField(blank=True, null=True)),
                ('actual_release_date', models.DateField(blank=True, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=20, null=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('transferred', 'Transferred'), ('deceased', 'Deceased'), ('escaped', 'Escaped')], default='active', max_length=20)),
                ('behavior_rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inmates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inmate',
                'verbose_name_plural': 'Inmates',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InmateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('education', 'Education'), ('vocational', 'Vocational Training'), ('counseling', 'Counseling'), ('therapy', 'Therapy'), ('work', 'Work Program'), ('religious', 'Religious Program'), ('recreation', 'Recreation')], max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='enrolled', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_or_score', models.CharField(blank=True, max_length=10, null=True)),
                ('certificate_earned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='prison.inmate')),
            ],
            options={
                'verbose_name': 'Inmate Program',
                'verbose_name_plural': 'Inmate Programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InmateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('regular', 'Regular Report'), ('urgent', 'Urgent Report'), ('disciplinary', 'Disciplinary Report'), ('medical', 'Medical Report'), ('behavioral', 'Behavioral Report'), ('incident', 'Incident Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='prison.inmate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inmate_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmate_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inmate Report',
                'verbose_name_plural': 'Inmate Reports',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_id_number', models.CharField(max_length=50)),
                ('visitor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(max_length=100)),
                ('visit_type', models.CharField(choices=[('family', 'Family Visit'), ('legal', 'Legal Visit'), ('official', 'Official Visit'), ('medical', 'Medical Visit'), ('religious', 'Religious Visit')], max_length=20)),
                ('visit_date', models.DateTimeField()),
                ('visit_duration_minutes', models.IntegerField()),
                ('purpose', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_visits', to=settings.AUTH_USER_MODEL)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='prison.inmate')),
            ],
            options={
                'verbose_name': 'Visitor Log',
                'verbose_name_plural': 'Visitor Logs',
                'ordering': ['-visit_date'],
            },
        ),
    ]
