# Generated by Django 5.2.3 on 2025-08-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmate',
            name='assignment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='assignment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='assignment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='disciplinary_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmate',
            name='last_health_check',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='medical_attention_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmate',
            name='protective_custody',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmate',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmatereport',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmatereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inmateprogram',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='enrolled', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('lawyer', 'Lawyer'), ('doctor', 'Doctor'), ('clergy', 'Clergy'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='visitor_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
